[Date]
date.timezone = "Asia/Shanghai"

expose_php= Off
memory_limit = 100M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 300

disable_functions = exec,passthru,shell_exec,system,proc_open,popen,assert,symlink,link
session.cookie_httponly = 1
session.use_strict_mode = 1
allow_url_fopen = Off
allow_url_include = Off
